NumPy Assignment


In [1]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

int64


In [5]:
#2. Given a NumPy array 'arr', check if its data type is float64.

import numpy as np
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


In [9]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

import numpy as np
arr = np.array([1+2j,2+3j,3+4j], dtype = np.complex128)
print(arr)

[1.+2.j 2.+3.j 3.+4.j]


In [11]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
import numpy as np
arr = np.array([1,2,3,4,5])
arr_float32 = arr.astype(np.float32)
print (arr_float32.dtype)

float32


In [1]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
import numpy as np

arr = np.array([1.23456789, 2.3456789, 3.456789, 4.56789, 5.6789], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)


[1.2345679 2.3456788 3.456789  4.56789   5.6789   ]
float32


In [3]:
#6. Write a function array_attributes that takes a NumPy array as input and
#returns its shape, size, and data type.

import numpy as np

def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

# Example:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (2, 3)
Size: 6
Data type: int64


In [4]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

import numpy as np

def array_dimension(arr):
    return arr.ndim

# Example:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Dimensionality of arr_1d:", array_dimension(arr_1d))
print("Dimensionality of arr_2d:", array_dimension(arr_2d))
print("Dimensionality of arr_3d:", array_dimension(arr_3d))


Dimensionality of arr_1d: 1
Dimensionality of arr_2d: 2
Dimensionality of arr_3d: 3


In [5]:
#8. Design a function item_size_info that takes a NumPy array as input and 
#returns the item size and the total size in bytes.
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

# Example:
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)
print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)


Item size (bytes): 8
Total size (bytes): 48


In [7]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

import numpy as np
def  array_strides(arr):
    return arr.strides
#Example:
  
arr = np.array([[1,2,3],[4,5,6]])
strides = array_strides(arr)
print("Strides:", strides)


Strides: (24, 8)


In [10]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and
#returns the shape and strides of the array.

import numpy as np
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
arr = np.array([[1,2,3], [4,5,6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:",strides)

Shape: (2, 3)
Strides: (24, 8)


In [11]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and 
#returns a NumPy array of zeros with `n` elements.

import numpy as np
def create_zeros_array(n):
    return np.zeros(n)
n = 3
zeros_array = create_zeros_array(n)
print(zeros_array)
    

[0. 0. 0.]


In [18]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
#NumPy array filled with ones of size `rows x cols`.

import numpy as np
def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))

rows = 3
cols = 5
ones_matrix = create_ones_matrix(rows,cols)
print(ones_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
#`step`.

import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example :
start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)


[1 3 5 7 9]


In [23]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
#(inclusive).

import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example:
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)


[0.   0.25 0.5  0.75 1.  ]


In [24]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye`.

import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

# Example:
n = 3
identity_matrix = create_identity_matrix(n)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#16. Write a function that takes a Python list and converts it into a NumPy array.

import numpy as np

def list_to_array(input_list):
    return np.array(input_list)

# Example:
python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_array(python_list)
print(numpy_array)


[1 2 3 4 5]


In [26]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
#same data

import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Use view to create a new array object with the same data
arr_view = arr.view()

# Modify the view to demonstrate that it's a separate object
arr_view[0] = 10

# Check the original array
print("Original array:", arr)

# Check the view array
print("View array:", arr_view)


Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]


In [27]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenate along axis 0 (rows)
result_axis0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:")
print(result_axis0)

# Concatenate along axis 1 (columns)
result_axis1 = concatenate_arrays(arr1, arr2.T, axis=1)
print("\nConcatenated along axis 1:")
print(result_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]]

Concatenated along axis 1:
[[1 2 5]
 [3 4 6]]


In [32]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

#concatenate`.

import numpy as np

# Create two NumPy arrays with different shapes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8], [9, 10]])

# Concatenate them vertically
result = np.concatenate((arr1, arr2), axis=0)
print(result)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [33]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

import numpy as np

def stack_arrays_vertically(arrays):
    return np.vstack(arrays)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

stacked_array = stack_arrays_vertically([arr1, arr2, arr3])
print(stacked_array)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [36]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
#with a given step size.

import numpy as np

def create_range_array(start, stop, step):
    return np.arange(start, stop + step, step, dtype=int)

start = 1
stop = 10
step = 2
range_array = create_range_array(start, stop, step)
print(range_array)


[ 1  3  5  7  9 11]


In [37]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
#(inclusive)

import numpy as np

def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)

values = generate_equally_spaced_values()
print(values)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [38]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
#1000 (inclusive).

import numpy as np

def generate_logarithmically_spaced_values():
    return np.logspace(0, 3, 5)

# Example usage
values = generate_logarithmically_spaced_values()
print(values)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [39]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
#are random integers between 1 and 100.

import numpy as np
import pandas as pd

# Create a NumPy array with random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

print(df)


   Column1  Column2  Column3
0       64       17      100
1       16       23       32
2       70       37        4
3       42       29       41
4       58       12       86


In [41]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
#with zeros. Use NumPy operations within the Pandas DataFrame

import numpy as np
import pandas as pd

def replace_negative_values(df, column_name):
    # Use numpy operations within the DataFrame to replace negative values with zeros
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example:
data = {'A': [-1, 2, -3, 4, -5],
        'B': [10, -20, 30, -40, 50]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A' with zeros
df = replace_negative_values(df, 'A')

print("\nDataFrame with negative values in column 'A' replaced with zeros:")
print(df)


Original DataFrame:
   A   B
0 -1  10
1  2 -20
2 -3  30
3  4 -40
4 -5  50

DataFrame with negative values in column 'A' replaced with zeros:
   A   B
0  0  10
1  2 -20
2  0  30
3  4 -40
4  0  50


In [44]:
#26.Access the 3rd element from the given NumPy array.
#arr = np.array([10, 20, 30, 40, 50])

import numpy as np
arr = np.array([10,20,30,40,50])

third_element = arr[2]
print(third_element)

30


In [45]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
#arr_2d = np.array([[1, 2, 3],
                  # [4, 5, 6],
                  # [7, 8, 9]])

import numpy as np

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

element_12 = arr_2d[1, 2]
print(element_12)
      


6


In [46]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
#arr = np.array([3, 8, 2, 10, 5, 7])

import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask of elements greater than 5
mask = arr > 5

# Use the mask to extract elements greater than 5
result = arr[mask]

print(result)


[ 8 10  7]


In [47]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
#arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform basic slicing to extract elements from index 2 to 5 (inclusive)
result = arr[2:6]

print(result)


[3 4 5 6]


In [48]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
#arr_2d = np.array([[1, 2, 3],
                  # [4, 5, 6],
                   #[7, 8, 9]])
        
import numpy as np

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Slice the 2D array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print(sub_array)
    

[[2 3]
 [5 6]]


In [50]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
#provided in another array

import numpy as np

def extract_elements_2d(arr, indices):
    return arr[indices]

# Example:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

indices = np.array([0, 2, 1, 2])  # Example indices to extract elements from each row

result = extract_elements_2d(arr_2d, indices)
print(result)


[[1 2 3]
 [7 8 9]
 [4 5 6]
 [7 8 9]]


In [51]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
#boolean indexing.

import numpy as np

def filter_elements(array, threshold):
    """
    Filters elements greater than a threshold from a given 1D array using boolean indexing.

    Parameters:
        array (numpy.ndarray): Input 1D array.
        threshold (float): Threshold value for filtering.

    Returns:
        numpy.ndarray: Filtered array.
    """
    filtered_array = array[array > threshold]
    return filtered_array

# Example:
array = np.array([1, 5, 10, 15, 20])
threshold = 10
filtered_result = filter_elements(array, threshold)
print(filtered_result)  # Output: [15 20]


[15 20]


In [52]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#separate arrays for each dimension.

import numpy as np

def extract_elements_3d(array, indices_dim1, indices_dim2, indices_dim3):
    """
    Extracts specific elements from a 3D array using indices provided in three separate arrays
    for each dimension.

    Parameters:
        array (numpy.ndarray): Input 3D array.
        indices_dim1 (numpy.ndarray): Array of indices for the first dimension.
        indices_dim2 (numpy.ndarray): Array of indices for the second dimension.
        indices_dim3 (numpy.ndarray): Array of indices for the third dimension.

    Returns:
        numpy.ndarray: Extracted elements.
    """
    extracted_elements = array[indices_dim1, indices_dim2, indices_dim3]
    return extracted_elements

# Example:
array_3d = np.random.randint(0, 10, size=(3, 4, 5))  # Example 3D array
indices_dim1 = np.array([0, 1, 2])
indices_dim2 = np.array([1, 2, 3])
indices_dim3 = np.array([2, 3, 4])
extracted_result = extract_elements_3d(array_3d, indices_dim1, indices_dim2, indices_dim3)
print(extracted_result)


[6 7 6]


In [53]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
#using boolean indexing.

import numpy as np

def satisfy_both_conditions(array, condition1, condition2):
    """
    Returns elements from an array where both two conditions are satisfied using boolean indexing.

    Parameters:
        array (numpy.ndarray): Input array.
        condition1 (numpy.ndarray): First boolean condition.
        condition2 (numpy.ndarray): Second boolean condition.

    Returns:
        numpy.ndarray: Elements satisfying both conditions.
    """
    satisfying_elements = array[np.logical_and(condition1, condition2)]
    return satisfying_elements

# Example usage:
array = np.array([1, 5, 10, 15, 20])
condition1 = array > 5
condition2 = array % 2 == 0
result = satisfy_both_conditions(array, condition1, condition2)
print(result)  # Output: [10 20]


[10 20]


In [54]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
#in separate arrays.

import numpy as np

def extract_elements_2d(array, row_indices, col_indices):
    """
    Extracts elements from a 2D array using row and column indices provided in separate arrays.

    Parameters:
        array (numpy.ndarray): Input 2D array.
        row_indices (numpy.ndarray): Array of row indices.
        col_indices (numpy.ndarray): Array of column indices.

    Returns:
        numpy.ndarray: Extracted elements.
    """
    extracted_elements = array[row_indices, col_indices]
    return extracted_elements

# Example:
array_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
extracted_result = extract_elements_2d(array_2d, row_indices, col_indices)
print(extracted_result)


[2 6 7]


In [55]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add scalar value of 5 to each element using broadcasting
result = arr + 5

print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [7]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
#corresponding element in arr1 using NumPy broadcasting.

import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

result = np.zeros((3, 4))

for i in range(3):
    result[i] = arr1[0][i] * arr2[i]

print(result)




[[ 1.  2.  3.  4.]
 [10. 12. 14. 16.]
 [27. 30. 33. 36.]]


In [8]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
#NumPy broadcasting.

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])

result = arr1[:, np.newaxis] + arr2

print(result)

[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [9]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
#broadcasting.

import numpy as np

# Define the arrays
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

# Add the arrays using broadcasting
result = arr1 + arr2

print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [13]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
#broadcasting. Handle the shape incompatibility.

import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[[1, 2],
                  [3, 4]],

                 [[5, 6],
                  [7, 8]]])

# Add a new axis to arr1
arr1_broadcasted = arr1[:, np.newaxis, np.newaxis, :]

# Perform multiplication using broadcasting
result = arr1_broadcasted * arr2

print("Result:\n", result)

In [14]:
#41. Calculate column wise mean for the given array:
#arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate the column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:\n", column_wise_mean)


Column-wise mean:
 [2.5 3.5 4.5]


In [15]:
#42. Find maximum value in each row of the given array:
#arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate the maximum value in each row
row_wise_max = np.max(arr, axis=1)

print("Maximum values in each row:\n", row_wise_max)


Maximum values in each row:
 [3 6]


In [16]:
#43. For the given array, find indices of maximum value in each column.
#arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate the index of the maximum value in each column
column_wise_max_index = np.argmax(arr, axis=1)

print("Indices of maximum values in each column:\n", column_wise_max_index)

Indices of maximum values in each column:
 [2 2]


In [18]:
#44. For the given array, apply custom function to calculate moving sum along rows.
#arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Define the custom moving sum function
def moving_sum(row, window_size):
    return np.convolve(row, np.ones(window_size), 'valid') / window_size

# Apply the custom function along rows
row_wise_moving_sum = np.apply_along_axis(func1d=moving_sum, axis=1, arr=arr, window_size=2)

print("Row-wise moving sum:\n", row_wise_moving_sum)


Row-wise moving sum:
 [[1.5 2.5]
 [4.5 5.5]]


In [20]:
#45. In the given array, check if all elements in each column are even.
#arr = np.array([[2, 4, 6], [3, 5, 7]])

import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in each column are even
if np.all(np.all(arr % 2 == 0, axis=0)):
    print("All elements in each column are even.")
else:
    print("Not all elements in each column are even.")

Not all elements in each column are even.


In [21]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
#reshaped matrix.
#original_array = np.array([1, 2, 3, 4, 5, 6])

import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3

reshaped_matrix = np.reshape(original_array, (m, n))

print("Reshaped matrix:\n", reshaped_matrix)

Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [22]:
#47. Create a function that takes a matrix as input and returns the flattened array.
#input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def flatten_matrix(input_matrix):
    return np.ravel(input_matrix)

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print("Flattened array:", flattened_array)

Flattened array: [1 2 3 4 5 6]


In [23]:
#48. Write a function that concatenates two given arrays along a specified axis.
#array1 = np.array([[1, 2], [3, 4]])
#array2 = np.array([[5, 6], [7, 8]])

import numpy as np

def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array = concatenate_arrays(array1, array2, axis=0)

print("Concatenated array (axis=0):\n", concatenated_array)

concatenated_array = concatenate_arrays(array1, array2, axis=1)

print("Concatenated array (axis=1):\n", concatenated_array)

Concatenated array (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated array (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]


In [26]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis
#original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

import numpy as np

def split_array(original_array, split_count, axis):
    shape = list(original_array.shape)
    shape[axis] = int(np.ceil(shape[axis] / split_count)) * split_count
    new_array = np.zeros(shape, dtype=original_array.dtype)
    new_array[:original_array.shape[0], :original_array.shape[1]] = original_array
    return np.split(new_array, split_count, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

split_arrays = split_array(original_array, split_count=2, axis=0)

print("Splitted arrays (axis=0):\n", split_arrays)

split_arrays = split_array(original_array, split_count=3, axis=1)

print("Splitted arrays (axis=1):\n", split_arrays)

Splitted arrays (axis=0):
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9],
       [0, 0, 0]])]
Splitted arrays (axis=1):
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [29]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
#original_array = np.array([1, 2, 3, 4, 5])
#indices_to_insert = [2, 4]
#values_to_insert = [10, 11]
#indices_to_delete = [1, 3]

import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)

    # Delete elements at specified indices
    for index in sorted(indices_to_delete, reverse=True):
        original_array = np.delete(original_array, index)

    return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Result array: \n", result)

Result array: 
 [ 1 10 11  4  5]


In [79]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
#Perform element-wise addition between `arr1` and `arr2`.

import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 100, size=10)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition between arr1 and arr2
result = arr1 + arr2

# Print the original arrays and the result of element-wise addition
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise addition:", result)


arr1: [ 2 90 19 40 57 49  2 97 93 32]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise addition: [  3  92  22  44  62  55   9 105 102  42]


In [38]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
#from 1 to 10. Subtract `arr2` from `arr1` element-wise.

import numpy as np

# Create a NumPy array `arr1` with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create a NumPy array `arr2` with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction between `arr1` and `arr2`
result = arr1 - arr2

print("Array `arr1`:\n", arr1)
print("Array `arr2`:\n", arr2)
print("Result of element-wise subtraction:\n", result)

Array `arr1`:
 [10  9  8  7  6  5  4  3  2  1]
Array `arr2`:
 [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction:
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [41]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
#Perform element-wise multiplication between `arr1` and `arr2`.

import numpy as np

# Create a NumPy array `arr1` with random integers
arr1 = np.random.randint(1, 10, size=(5, 5))

# Create a NumPy array `arr2` with integers from 1 to 5
arr2 = np.arange(1, 6)

# Repeat `arr2` along the first axis to match the shape of `arr1`
arr2 = np.repeat(arr2[:, None], arr1.shape[1], axis=1)

# Perform element-wise multiplication between `arr1` and `arr2`
result = arr1 * arr2

print("Array `arr1`:\n", arr1)
print("Array `arr2`:\n", arr2)
print("Result of element-wise multiplication:\n", result)


Array `arr1`:
 [[2 4 8 8 5]
 [8 3 6 7 4]
 [8 9 4 8 7]
 [8 2 3 3 1]
 [1 6 3 1 5]]
Array `arr2`:
 [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
Result of element-wise multiplication:
 [[ 2  4  8  8  5]
 [16  6 12 14  8]
 [24 27 12 24 21]
 [32  8 12 12  4]
 [ 5 30 15  5 25]]


In [42]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
#to 5. Perform element-wise division of `arr1` by `arr2`.

import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 10+1, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 5+1)

# Perform element-wise division
result = arr1 / arr2

# Print the result
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)


arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [43]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
#reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 5+1)

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Calculate the exponentiation of arr1 raised to the power of arr2 element-wise
result = np.power(arr1, arr2)

# Print the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise exponentiation:", result)



arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result of element-wise exponentiation: [ 1 16 27 16  5]


In [44]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

import numpy as np

def count_substring_occurrences(arr, substring):
    """
    Count the occurrences of a specific substring within a NumPy array of strings.

    Parameters:
        arr (numpy.ndarray): NumPy array of strings.
        substring (str): The substring to count occurrences of.

    Returns:
        int: Number of occurrences of the substring within the array.
    """
    # Convert the array to a list of strings for easier manipulation
    arr_list = arr.tolist()
    
    # Count occurrences of the substring in each string
    occurrences = [string.count(substring) for string in arr_list]
    
    # Return the total count
    return sum(occurrences)

# Test the function
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}' in the array: {occurrences}")


Occurrences of 'hello' in the array: 3


In [45]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
#arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

import numpy as np

def extract_uppercase_characters(arr):
    """
    Extract uppercase characters from a NumPy array of strings.

    Parameters:
        arr (numpy.ndarray): NumPy array of strings.

    Returns:
        list: List of uppercase characters extracted from the array.
    """
    # Convert the array to a list of strings for easier manipulation
    arr_list = arr.tolist()
    
    # Initialize an empty list to store uppercase characters
    uppercase_chars = []
    
    # Iterate through each string in the array
    for string in arr_list:
        # Extract uppercase characters from the string using list comprehension
        uppercase_chars.extend([char for char in string if char.isupper()])
    
    # Return the list of uppercase characters
    return uppercase_chars

# Test the function
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase_characters(arr)
print("Uppercase characters extracted from the array:", uppercase_chars)


Uppercase characters extracted from the array: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [46]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

# Example usage:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = replace_substring(arr, 'a', 'x')
print(result)

['xpple' 'bxnxnx' 'grxpe' 'pinexpple']


In [50]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
#arr1 = np.array(['Hello', 'World'])
#arr2 = np.array(['Open', 'AI'])

import numpy as np

def concatenate_strings(arr1, arr2):
    """
    Concatenate strings in two NumPy arrays element-wise.

    Parameters:
        arr1 (numpy.ndarray): First NumPy array of strings.
        arr2 (numpy.ndarray): Second NumPy array of strings.

    Returns:
        numpy.ndarray: NumPy array containing the concatenated strings.
    """
    # Concatenate strings element-wise using list comprehension
    concatenated_arr = np.array([s1 + s2 for s1, s2 in zip(arr1, arr2)])

    return concatenated_arr

# Test the function
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_arr = concatenate_strings(arr1, arr2)
print("Concatenated array:")
print(concatenated_arr)



Concatenated array:
['HelloOpen' 'WorldAI']


In [51]:
#60. Write a function that finds the length of the longest string in a NumPy array.
#arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

def longest_string_length(arr):
    """
    Find the length of the longest string in a NumPy array.

    Parameters:
        arr (numpy.ndarray): NumPy array of strings.

    Returns:
        int: Length of the longest string in the array.
    """
    # Convert the array to a list of strings for easier manipulation
    arr_list = arr.tolist()
    
    # Find the length of the longest string using max() function with key=len
    longest_length = len(max(arr_list, key=len))
    
    return longest_length

# Test the function
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest_string_length(arr)
print("Length of the longest string in the array:", longest_length)


Length of the longest string in the array: 9


In [52]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
#standard deviation of the dataset using NumPy's functions.

import numpy as np

# Generate the dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean using np.mean()
mean = np.mean(dataset)

# Compute the median using np.median()
median = np.median(dataset)

# Compute the variance using np.var()
variance = np.var(dataset)

# Compute the standard deviation using np.std()
std_deviation = np.std(dataset)

# Print the results
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [464  51  71 549 475 762 421 248  11 767 304 590 759 606 803 205 693 723
 843 961 687 311  35 734 825  56 374 930 721 586 203 875 412 999  72 487
 952 345 657 225 884 815 878 817 243 544 237 361 499 436 894 908 933 208
 939 424 933 209  14 634 529 920 641 504 563 846 152 117 878 834 170  94
 884 175 339  45 656 223 707 178 326  63  33 904 504 998 905 884 941 862
 770  42 823 433 324 262 133 543  86 236]
Mean: 521.29
Median: 536.0
Variance: 95778.5459
Standard Deviation: 309.481091344851


In [53]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
#dataset.

import numpy as np

# Generate the array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Find the 25th percentile using np.percentile()
percentile_25 = np.percentile(dataset, 25)

# Find the 75th percentile using np.percentile()
percentile_75 = np.percentile(dataset, 75)

# Print the results
print("Dataset:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Dataset: [82 88 53 25  4  1 86 18 50 79 17 99 23 34 26 63 25 29 32 56 66 75  3 83
 47  4 83 28 41 53 76 24  1 48 55 91 64 20 75 15 79 79 83  8 54 43 65 21
 75 22]
25th Percentile: 23.25
75th Percentile: 75.0


In [54]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
#arrays using NumPy's `corrcoef` function.

import numpy as np

# Create two arrays representing two sets of variables
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient using np.corrcoef()
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

# Print the correlation coefficient
print("Correlation Coefficient between array1 and array2:", correlation_coefficient)


Correlation Coefficient between array1 and array2: -0.9999999999999999


In [55]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

import numpy as np

# Define the matrices
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Perform matrix multiplication
result = np.dot(matrix_a, matrix_b)

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nResult of matrix multiplication:")
print(result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [56]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
#percentiles along with the first and third quartiles.

import numpy as np

# Create an array of 50 integers between 10 and 1000
data = np.random.randint(10, 1000, size=50)

# Calculate percentiles
percentiles = np.percentile(data, [10, 25, 50, 75, 90])

print("Array of 50 integers between 10 and 1000:")
print(data)
print("\n10th Percentile:", percentiles[0])
print("25th Percentile (First Quartile):", percentiles[1])
print("50th Percentile (Median):", percentiles[2])
print("75th Percentile (Third Quartile):", percentiles[3])
print("90th Percentile:", percentiles[4])


Array of 50 integers between 10 and 1000:
[439 564 584 119 952 573 814 499 801 901 409 205 822 106 555 483 965 890
 352 408 818 191 157 937 423 544  93  35 794  61 140 782 606 319 967 142
 378 592  89 268 561 542 725 386 843 397 338 347 170 951]

10th Percentile: 117.7
25th Percentile (First Quartile): 280.75
50th Percentile (Median): 491.0
75th Percentile (Third Quartile): 791.0
90th Percentile: 904.6


In [57]:
#66. Create a NumPy array of integers and find the index of a specific element

import numpy as np

# Create a NumPy array of integers
arr = np.array([2, 4, 6, 8, 10, 12, 14, 16])

# Element to find
element_to_find = 10

# Find the index of the element
index = np.where(arr == element_to_find)[0]

if len(index) > 0:
    print("Element", element_to_find, "found at index:", index[0])
else:
    print("Element", element_to_find, "not found in the array.")


Element 10 found at index: 4


In [58]:
#67. Generate a random NumPy array and sort it in ascending order.

import numpy as np

# Generate a random NumPy array
random_array = np.random.rand(10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Random array:")
print(random_array)
print("\nSorted array in ascending order:")
print(sorted_array)


Random array:
[0.81268603 0.64464147 0.5887382  0.60063323 0.58003112 0.43228422
 0.61943646 0.95709572 0.01639158 0.36936787]

Sorted array in ascending order:
[0.01639158 0.36936787 0.43228422 0.58003112 0.5887382  0.60063323
 0.61943646 0.64464147 0.81268603 0.95709572]


In [59]:
#68. Filter elements >20  in the given NumPy array
#arr = np.array([12, 25, 6, 42, 8, 30])

import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements > 20
filtered_array = arr[arr > 20]

print("Original array:")
print(arr)
print("\nFiltered array with elements > 20:")
print(filtered_array)


Original array:
[12 25  6 42  8 30]

Filtered array with elements > 20:
[25 42 30]


In [60]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
#arr = np.array([1, 5, 8, 12, 15])

import numpy as np

arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_array = arr[arr % 3 == 0]

print("Original array:")
print(arr)
print("\nFiltered array with elements divisible by 3:")
print(filtered_array)


Original array:
[ 1  5  8 12 15]

Filtered array with elements divisible by 3:
[12 15]


In [61]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 (inclusive)
filtered_array = arr[(arr >= 20) & (arr <= 40)]

print("Original array:")
print(arr)
print("\nFiltered array with elements ≥ 20 and ≤ 40:")
print(filtered_array)


Original array:
[10 20 30 40 50]

Filtered array with elements ≥ 20 and ≤ 40:
[20 30 40]


In [62]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
#arr = np.array([1, 2, 3])

import numpy as np

arr = np.array([1, 2, 3])

# Check byte order
byte_order = arr.dtype.byteorder

print("Byte order of the array:", byte_order)


Byte order of the array: =


In [63]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
#arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

print("Array after byte swapping in place:")
print(arr)


Array after byte swapping in place:
[16777216 33554432 50331648]


In [64]:
#73. For the given NumPy array, swap its byte order without modifying the original array using
#`newbyteorder()`.
#arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying original array
swapped_arr = arr.newbyteorder()

print("Original array:")
print(arr)
print("\nArray with swapped byte order:")
print(swapped_arr)


Original array:
[1 2 3]

Array with swapped byte order:
[16777216 33554432 50331648]


In [65]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using
#`newbyteorder()`.
#arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

# Conditionally swap byte order based on system endianness
if sys.byteorder == 'little':
    swapped_arr = arr.newbyteorder('big')
else:
    swapped_arr = arr.newbyteorder('little')

print("Original array:")
print(arr)
print("\nArray with swapped byte order based on system endianness:")
print(swapped_arr)


Original array:
[1 2 3]

Array with swapped byte order based on system endianness:
[16777216 33554432 50331648]


In [66]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
#attribute `byteorder`.
#arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
byte_order = arr.dtype.byteorder

if byte_order == '=':
    print("No byte swapping necessary for the current system.")
elif byte_order == '|':
    print("Byte swapping is necessary for the current system.")
else:
    print("Unknown byte order:", byte_order)


No byte swapping necessary for the current system.


In [67]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
#an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

import numpy as np

# Create arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original arr1:")
print(arr1)
print("\nModified copy_arr:")
print(copy_arr)


Original arr1:
[ 1  2  3  4  5  6  7  8  9 10]

Modified copy_arr:
[100   2   3   4   5   6   7   8   9  10]


In [68]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
#the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

import numpy as np

# Create a 2D NumPy array matrix of shape (3, 3) with random integers
matrix = np.random.randint(0, 100, size=(3, 3))

# Extract a slice view_slice from the matrix
view_slice = matrix[1:, 1:]

# Modify an element in view_slice
view_slice[0, 0] = 999

# Check if modifying view_slice changes the original matrix
print("Original matrix:")
print(matrix)
print("\nModified view_slice:")
print(view_slice)


Original matrix:
[[ 42   0  50]
 [ 34 999   2]
 [ 14  13  30]]

Modified view_slice:
[[999   2]
 [ 13  30]]


In [69]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
#`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

import numpy as np

# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice view_b from array_a
view_b = array_a[1:3, 1:3]

# Broadcast the addition of 5 to view_b
view_b += 5

# Check if it alters the original array_a
print("Original array_a:")
print(array_a)
print("\nModified view_b:")
print(view_b)


Original array_a:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]

Modified view_b:
[[10 11]
 [13 14]]


In [70]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
#`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#reflects changes in the original `orig_array`.

import numpy as np

# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view reshaped_view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Check if it reflects changes in the original orig_array
print("Original orig_array:")
print(orig_array)
print("\nModified reshaped_view:")
print(reshaped_view)


Original orig_array:
[[100   2   3   4]
 [  5   6   7   8]]

Modified reshaped_view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [73]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
#elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

import numpy as np

# Create a NumPy array data of shape (3, 4) with random integers
data = np.random.randint(0, 10, size=(3, 4))

# Extract a copy data_copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
data_copy[0] = 100

# Verify if it affects the original data
print("Original data:")
print(data)
print("\nModified data_copy:")
print(data_copy)


Original data:
[[1 1 2 5]
 [4 7 9 7]
 [8 3 0 7]]

Modified data_copy:
[100   9   7   8   7]


In [74]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
#operations between them.

import numpy as np

# Define the shape of the matrices
shape = (3, 3)

# Create matrices A and B of identical shape containing random integers
A = np.random.randint(0, 10, size=shape)
B = np.random.randint(0, 10, size=shape)

# Perform addition and subtraction operations between matrices A and B
addition_result = A + B
subtraction_result = A - B

# Print the original matrices and the results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition result (A + B):")
print(addition_result)
print("\nSubtraction result (A - B):")
print(subtraction_result)


Matrix A:
[[8 9 1]
 [0 5 0]
 [7 1 5]]

Matrix B:
[[5 2 4]
 [0 6 9]
 [1 3 0]]

Addition result (A + B):
[[13 11  5]
 [ 0 11  9]
 [ 8  4  5]]

Subtraction result (A - B):
[[ 3  7 -3]
 [ 0 -1 -9]
 [ 6 -2  5]]


In [75]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

import numpy as np

# Generate matrices C (3x2) and D (2x4)
C = np.random.randint(0, 10, size=(3, 2))
D = np.random.randint(0, 10, size=(2, 4))

# Perform matrix multiplication
multiplication_result = np.dot(C, D)

# Print the matrices and the result of multiplication
print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nMatrix multiplication result (C * D):")
print(multiplication_result)


Matrix C (3x2):
[[7 4]
 [0 9]
 [2 4]]

Matrix D (2x4):
[[0 6 4 3]
 [8 4 2 2]]

Matrix multiplication result (C * D):
[[32 58 36 29]
 [72 36 18 18]
 [32 28 16 14]]


In [76]:
#83. Create a matrix `E` and find its transpose.

import numpy as np

# Create a matrix E
E = np.array([[1, 2, 3],
              [4, 5, 6]])

# Find the transpose of matrix E
E_transpose = np.transpose(E)

# Print the original matrix and its transpose
print("Matrix E:")
print(E)
print("\nTranspose of matrix E:")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of matrix E:
[[1 4]
 [2 5]
 [3 6]]


In [77]:
#84. Generate a square matrix `F` and compute its determinant.

import numpy as np

# Generate a square matrix F
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the matrix F and its determinant
print("Matrix F:")
print(F)
print("\nDeterminant of matrix F:", determinant_F)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F: 0.0


In [78]:
#85. Create a square matrix `G` and find its inverse.

import numpy as np

# Create a square matrix G
G = np.array([[1, 2],
              [3, 4]])

# Find the inverse of matrix G
inverse_G = np.linalg.inv(G)

# Print the matrix G and its inverse
print("Matrix G:")
print(G)
print("\nInverse of matrix G:")
print(inverse_G)


Matrix G:
[[1 2]
 [3 4]]

Inverse of matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
